export enum Controller {
  AUTH = 'auth',
  RECOVERY = 'recovery',
  SECURITY = 'security',
  USERS = 'users',
  CONFIRMATION_HASH = 'confirmation-hash',
  ARTICLES = 'articles',
  ABOUT_BLOG = 'about-blog',
  ABOUT = 'about',
  CHANGELOG = 'changelog',
  LICENSE = 'license',
  PRIVACY = 'privacy',
  STATIC_ASSETS = 'static-assets',
  SITE_CONFIG = 'site-config',
  PAGES = 'pages',
  FAQ = 'faq',
  HOME = 'home',
  CONTACT = 'contact',
  NEWSLETTERS = 'newsletters',
  PROJECTS = 'projects',
  MENU = 'menu',
  MAINTENANCE = 'maintenance'
}
